repos:
  - repo: local
    hooks:
      - id: oxlint
        name: oxlint
        entry: pnpm exec oxlint
        language: system
        types: [javascript, jsx, ts, tsx, vue]
        pass_filenames: false

      - id: oxfmt
        name: oxfmt
        entry: pnpm exec oxfmt
        language: system
        types: [javascript, jsx, ts, tsx, vue]
        exclude: "CHANGELOG.md"
        pass_filenames: false

      - id: type-check
        name: TypeScript type check
        entry: pnpm run type:check
        language: system
        types: [ts, tsx, vue]
        pass_filenames: false
