name: Versions

on:
  workflow_call:

jobs:
  versions:
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.set.outputs.node-version }}
      pnpm-version: ${{ steps.set.outputs.pnpm-version }}
    steps:
      - name: Set versions
        id: set
        run: |
          echo "node-version=22.20.0" >> $GITHUB_OUTPUT
          echo "bun-version=1.3.3" >> $GITHUB_OUTPUT

      - name: Output versions
        run: |
          echo "Node.js: ${{ steps.set.outputs.node-version }}"
          echo "bun: ${{ steps.set.outputs.bun-version }}"
